# Generated by Django 4.2.3 on 2023-07-21 14:32

from django.db import migrations
import portfolio_site.pages.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_homepage_body_alter_homepage_button_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(label="Heading")),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic", "link", "or", "ul"],
                                        label="Text",
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image"
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "featured_blog_posts",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(label="Heading")),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        label="Text", required=False
                                    ),
                                ),
                                (
                                    "posts",
                                    wagtail.blocks.ListBlock(
                                        portfolio_site.pages.blocks.FeaturedBlogPostItemBlock,
                                        label="Posts",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                null=True,
                use_json_field=True,
                verbose_name="body",
            ),
        ),
    ]
